site_name: geuebt-core
site_url: https://nrw-geubt.github.io/geuebt-core/
site_description: Core module of NRW-Geübt
site_author: Gregoire Denay
copyright: BSD 3-Clause license

repo_url: https://github.com/NRW-GEUBT/geuebt-core

nav:
  - Welcome: index.md
  - Guide for users: user_guide.md
  - Guide for developers: dev_guide.md
  - About: 
      - License: about/license.md
      - Release notes: about/changelog.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    favicon: material/dna
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: >
  Copyright &copy; 2023 Grégoire Denay -
  <a href="#__consent">Change cookie settings</a>
