# Integration test config
# ----------------------


workdir: .tests/integration

watched_folders: 
  - data/input_1
  - data/input_2
  # - data/input_3

max_threads_per_job: 1

# Should watched dirs be emptied?
cleanup_watched_dirs: False
ephemeral: False

# Database
# --------

API_url: "http://127.0.0.1:8010"

